name: paynet_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_phone_direct_caller: ^2.1.1
  flutter_screenutil: ^5.5.3+2
  loop_page_view: ^1.2.0
  flutter_svg: ^1.1.1+1
  animations: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/logo.png
    - assets/images/
    - assets/fonts/
    - assets/icons/
  
  fonts:
    - family: dosis
      fonts:
        - asset: assets/fonts/dosis.ttf
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
